app/models.py
from . import db

from datetime import datetime
import pytz

fuso_sp = pytz.timezone('America/Sao_Paulo')

def horario_sp():
    return datetime.now(fuso_sp)

class Historias(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    historia = db.Column(db.Text, nullable=False)
    dificuldade = db.Column(db.String(20), nullable=False)
    data_criacao = db.Column(db.DateTime, default=horario_sp)
    coerencia = db.Column(db.String(20), nullable=False)
    diversao = db.Column(db.String(20), nullable=False)
    gramatica = db.Column(db.String(20), nullable=False)
    moral = db.Column(db.String(20), nullable=False)
    relacaofrase = db.Column(db.String(20), nullable=False)
    media = db.Column(db.String(20), nullable=False)
    frase = db.Column(db.Text, nullable=False)

app/__init__.py
from flask_sqlalchemy import SQLAlchemy
from flask import Flask
from dotenv import load_dotenv

db = SQLAlchemy()

def create_app():
    load_dotenv()
    
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'skrevastorias'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///skreva.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)

    from .routes.main import main
    app.register_blueprint(main)

    with app.app_context():
        db.create_all()

    return app

app/routes/main.py
from flask import Blueprint, render_template, redirect, session, url_for, request
from openai import OpenAI
from app import db
from app.models import Historias
import re

main = Blueprint('main', __name__)

client = OpenAI(
base_url="https://openrouter.ai/api/v1",
api_key="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",
)

@main.route('/')
def index():
    session.pop('frase', None)
    
    if 'dificuldade' not in session or session['dificuldade'] is None:
        session['dificuldade'] = 'Médio'

    dificuldade = session.get('dificuldade')

    return render_template('index.html', dificuldade=dificuldade)

@main.route('/gerar_frase')
def gerar_frase():
    try:
        resposta = client.completions.create(
            model="openai/gpt-4.1",
            prompt="Crie uma frase bem curta, engraçada e aleatória que esteja dentro do contexto de uma história/conversa para que o usuário crie uma história em que essa frase se encaixe nela. EXEMPLO:'Até que finalmente, eu descobri o que era ser um vilão de verdade', ou 'A vida é como uma caixa de chocolates, você nunca sabe o que vai encontrar'. A frase deve ter até 10 palavras e fazer sentido. Não adicione explicações, apenas a frase.",
            max_tokens=25,
            temperature=1.4
        )
        frase_gerada = resposta.choices[0].text.strip()
        session['frase'] = frase_gerada
        return redirect(url_for('main.history'))
        
    except Exception as erro:
        session['frase'] = f"Erro ao gerar frase: {erro}"
        return redirect(url_for('main.history'))

@main.route('/history')
def history():
    frase = session.get('frase', None)
    dificuldade = session.get('dificuldade')
    
    if dificuldade == 'Fácil':
        caracteres = 500
        tempo = 300
        
    elif dificuldade == 'Médio':
        caracteres = 300
        tempo = 180
        
    elif dificuldade == 'Difícil':
        caracteres = 200
        tempo = 120
    
    else:
        caracteres = session.get('caracteres')
        tempo = session.get('tempo')
        
    return render_template('history.html', frase=frase, dificuldade=session['dificuldade'], caracteres=caracteres, tempo=tempo)

@main.route('/resultado', methods=['POST'])
def resultado():
    frase = session.get('frase', None)
    historia = request.form.get('historia')

    resultado = client.completions.create(
        model="openai/gpt-4.1",
        prompt=f"De acordo com a história: {historia}, gostaria que você a avaliasse rigorosamente, a história deve ter começo, meio e fim. Com introdução, desenvolvimento e conclusão. Avalie-a de acordo com os 5 elementos da narrativa e se ela se encaixa no gênero história. Leve em consideração esses pontos: 📚 Coerência, 🧠 Criatividade, 📝 Qualidade gramatical e textual, 🎯 Moral ou mensagem e 🔗 Relação com a frase: {frase}. A avaliação deve ser feita em uma escala de 0 a 10, onde 0 é o pior e 10 é o melhor. Explique de forma bem breve o motivo da nota. Exemplo: 📚 Coerência: 8 - Pois é uma leitura fácil e não é confusa. (...) ATENÇÃO: TIRE OS '**' DA AVALIAÇÃO. no número 6, apenas diga a nota e o motivo sem repetir a frase. Depois, faça a média das notas (Ex: 🔢 Média final: 8), na hora de avaliar a relação com a frase, faça assim: '🔗 Relação com a frase: 8' e não apenas o emoji. APENAS DÊ AS NOTAS, A MÉDIA E OS MOTIVOS! Se não houver história, apenas diga: 'Você não enviou uma história... Tente denovo, por favor.' Se a história conter palavras ofensivas/desrespeitoso, apenas diga: 'A história enviada contém conteúdo ofensivo e desrespeitoso. Não posso avaliá-la.'",
        max_tokens=300,
        temperature=0
    )
    
    media = client.completions.create(
        model="openai/gpt-4.1",
        prompt=f"Qual a média das notas: {resultado.choices[0].text.strip()}? Responda apenas com a média, sem explicações.",
        max_tokens=50,
        temperature=0
    )
    
    media_final = media.choices[0].text.strip()
    
    def extrair_nota(emoji, texto):
        padrao = rf"{re.escape(emoji)}.*?:\s*(\d+)"
        match = re.search(padrao, texto)
        return match.group(1) if match else "0"

    resultado_texto = resultado.choices[0].text.strip()

    coerencia = extrair_nota("📚", resultado_texto)
    diversao = extrair_nota("🧠", resultado_texto)
    gramatica = extrair_nota("📝", resultado_texto)
    moral = extrair_nota("🎯", resultado_texto)
    relacao = extrair_nota("🔗", resultado_texto)
    
    resultado_texto = resultado.choices[0].text.strip()
    
    nova_historia = Historias(
        historia=historia,
        dificuldade=session.get('dificuldade', 'Médio'),
        coerencia=coerencia,
        diversao=diversao,
        gramatica=gramatica,
        moral=moral,
        relacaofrase=relacao,
        media=media_final,
        frase=frase
    )
    
    if "Você não enviou uma história" not in resultado_texto and "ofensivo e desrespeitoso" not in resultado_texto:
        db.session.add(nova_historia)
        db.session.commit()


    return render_template('result.html', frase=frase, historia=historia, resultado=resultado_texto, media=media_final, dificuldade=session.get('dificuldade', 'Médio'), nota_media=media.choices[0].text.strip())
    
@main.route('/configuracoes')
def configuracoes():
    dificuldade = session.get('dificuldade')
    tempo = session.get('tempo')
    caracteres = session.get('caracteres')
    
    return render_template('settings.html', dificuldade=dificuldade, tempo=tempo, caracteres=caracteres)

@main.route('/salvarconfiguracoes')
def salvarconfiguracoes():
    dificuldadeSelecionada = request.args.get('dificuldade')
    tempoSelecionado = request.args.get('tempo')
    caracteresSelecionado = request.args.get('caracteres')
    
    session['dificuldade'] = dificuldadeSelecionada
    session['tempo'] = tempoSelecionado
    session['caracteres'] = caracteresSelecionado
    
    return redirect(url_for('main.index'))

@main.route('/historias')
def historias_salvas():
    historias = Historias.query.all()
    return render_template('stories.html', historias=historias)

@main.route('/historia/<int:id>')
def historia(id):
    historia = Historias.query.get_or_404(id)
    return render_template('storia.html', historia=historia)

@main.route('/melhoresStorIAs')
def melhores_historias():
    historias = Historias.query.order_by(db.cast(Historias.media, db.Float).desc()).limit(3).all()
    return render_template('beststories.html', historias=historias)

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Skreva StorIAs{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/icon.png') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
</head>

<body>
    <header>
        <div style="display: flex; justify-content: center; align-items: center;">
            <img src="{{ url_for('static', filename='img/icon.png') }}" alt="" width="50" style="margin-right: 1%;">
            <h2>Skreva StorIAs</h2>
        </div>
        <nav>
            <a href="/">Início</a>
            <a href="/melhoresStorIAs">Melhores histórias</a>
            <a href="/historias">Histórias</a>
            <a href="/configuracoes">Configurações</a>
        </nav>
    </header>

    <main class="container">
        {% block content %}{% endblock %}
    </main>

    <footer>
        <p>Conteúdo gerado por IA - Nada produzido aqui tem relação com a vida real.</p>
        <p>Desenvolvido por Igor Verneque</p>
        <p>Skreva StorIAs v4.5</p>
        <div style="display: flex; align-items: center;">
            <p style="margin-right: 10px;">LinkedIn: </p>
            <a href="https://www.linkedin.com/in/igor-verneque/" target="blank">
                <img src="{{ url_for('static', filename='img/linkedin.png') }}" width="25" alt="">
            </a>
        </div>

        <div style="display: flex; align-items: center;">
            <p style="margin-right: 10px;">GitHub: </p>
            <a href="https://github.com/IgorVernequeDev" target="blank">
                <img src="{{ url_for('static', filename='img/github.png') }}" width="30" alt="">
            </a>
        </div>
    </footer>

    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>

</html>

app/templates/beststories.html
{% extends "base.html" %}

{% block title %}Melhores Histórias - Skreva StorIAs{% endblock %}

{% block content %}
    <div style="display: flex; width: 100%; justify-content: space-around; align-items: center;">
        <h1>🏆 Melhores Histórias</h1>
        <p>Clique para vê-las individualmente!</p>
    </div>
    <br>
    {% for historia in historias %}
        <a href="/historia/{{ historia.id }}" style="color: inherit;">
            <div class="historia">
                <h4>Frase: {{ historia.frase }}</h4>
                <br>
                <p>{{ historia.historia }}</p>
                <div class="avaliacoes">
                    Diversão: {{ historia.diversao }} |
                    Coerência: {{ historia.coerencia }} |
                    Qualidade gramatical: {{ historia.gramatica }} |
                    Moral: {{ historia.moral }} |
                    Relação com a frase: {{ historia.relacaofrase }} |
                    <strong>Média: {{ historia.media }}</strong>
                </div>
            </div>
        </a>
    {% else %}
        <p>Nenhuma história criada ainda. Comece criando uma!</p>
    {% endfor %}

{% endblock %}

app/templates/history.html
{% extends "base.html" %}

{% block title %}História - Skreva StorIAs{% endblock %}

{% block content %}
{% if not frase %}
<div id="divFraseInicial">
    <h1>Pronto pra começar?</h1>
    <br>
    <p>Gere sua frase aleatória!</p>
</div>
<div>
    <br>

    <a href="{{ url_for('main.gerar_frase') }}">
        <button type="submit">Gerar Frase</button>
    </a>
    {% endif %}
    <div id="divTitulo">
        <h2 id="timerText" style="display: none; text-align: center;">⏳ Tempo restante: <span id="timer">00:00</span>
        </h2>
        <h3 id="caracteresRestantes" style="display: none;">Caracteres restantes:<span id="contador"> {{ caracteres
                }}</span></h3>
    </div>
    <br>
</div>

{% if frase %}
<h3>Frase gerada: {{ frase }}</h3>
<br>

<p>Ótimo! Agora vamos criar sua história.</p>
<br>

<button onclick="comecarHistoria()" id="comecarHistoria">Começar</button>
<br>

<form id="formHistoria" style="display: none;" action="{{ url_for('main.resultado') }}" method="POST">
    <textarea name="historia" id="historia" rows="10" cols="50" maxlength="{{ caracteres }}"
        placeholder="Escreva sua história aqui..."></textarea>
    <br>
    <br>
    <div style="text-align: center;">
        <button id="enviarHistoria" type="submit">Enviar</button>
    </div>
</form>

<script>
    function comecarHistoria() {

        document.getElementById('formHistoria').style.display = 'block';
        document.getElementById('comecarHistoria').style.display = 'none';
        document.getElementById('timerText').style.display = 'block';
        document.getElementById('caracteresRestantes').style.display = 'block';
        
        let tempoRestante = parseInt("{{ tempo }}");

        const timerDisplay = document.getElementById("timer");
        const textarea = document.querySelector('textarea');
        const contador = document.getElementById('contador');
        const limite = parseInt(textarea.getAttribute('maxlength'));
        const buttonEnviarHistoria = document.getElementById('enviarHistoria');

        function atualizarTimer() {
            const minutos = Math.floor(tempoRestante / 60).toString().padStart(2, '0');
            const segundos = (tempoRestante % 60).toString().padStart(2, '0');
            timerDisplay.textContent = `${minutos}:${segundos}`;

            if (tempoRestante <= 0) {
                clearInterval(intervalo);
                textarea.readOnly = true;
                timerDisplay.textContent = "Tempo esgotado!";
            }

            tempoRestante--;
        }

        const intervalo = setInterval(atualizarTimer, 1000);
        atualizarTimer();

        textarea.addEventListener('input', () => {
            const restante = limite - textarea.value.length;
            contador.textContent = " " + restante;
        });

        formHistoria = document.getElementById("formHistoria");
        formHistoria.style.display = "block";

        comecarHistoria = document.getElementById("comecarHistoria");
        comecarHistoria.style.display = "none";

        timerText = document.getElementById("timerText");
        timerText.style.display = "block";

        caracteresRestantes = document.getElementById("caracteresRestantes");
        caracteresRestantes.style.display = "block";

    }

    buttonEnviarHistoria.addEventListener('click', (e) => {
        if (textarea.value.trim() === "") {
            e.preventDefault();
            alert("Você ainda não escreveu sua história!");
        }
    });

    const fraseTexto = document.querySelector('h3');
    if (fraseTexto) {
        fraseTexto.addEventListener('copy', (e) => e.preventDefault());
        fraseTexto.addEventListener('cut', (e) => e.preventDefault());
        fraseTexto.addEventListener('contextmenu', (e) => e.preventDefault());
        fraseTexto.setAttribute('draggable', 'false');
    }

    window.comecarHistoria = comecarHistoria;
</script>

{% endif %}

{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Início - Skreva StorIAs{% endblock %}

{% block content %}
<div style="text-align: center;">
    <h2>Bem-vindo ao Skreva StorIAs!</h2>
    <p style="font-size: 18px; margin-top: 1%; margin-bottom: 1%;">Dificuldade: {{ dificuldade }}</p>
</div>
<p style="font-size: 16px; text-align: center;">
    Aqui, a inteligência artificial irá te dar uma <strong>frase curta e aleatória</strong> para inspirar sua
    criatividade. Depois disso, você irá escrever uma história com base nessa frase e nos 5 elementos da
    narrativa:<strong> enredo, narrador, personagens, tempo e espaço.</strong> Você tem tempo limitado para escrever,
    então seja rápido! E ao final, a IA irá avaliar sua história <strong>rigorosamente</strong>, com base em critérios
    como:
</p>
<br>

<ul style="font-size: 16px;">
    <li>- 📚 Coerência</li>
    <li>- 🧠 Criatividade</li>
    <li>- 📝 Qualidade gramatical e textual</li>
    <li>- 🎯 Moral ou mensagem</li>
    <li>- 🔗 Relação com a frase</li>
</ul>

<br>
<p style="font-size: 16px;">Clique no botão abaixo para começar sua jornada!</p>
<br>
<div style="text-align: center;">
    <a href="{{ url_for('main.history') }}">
        <button>Começar Agora</button>
    </a>
</div>
{% endblock %}

app/templates/result.html
{% extends 'base.html' %}

{% block title %}Resultado - Skreva StorIAs{% endblock %}

{% block content %}
{% if resultado %}
<h2>Resultado da Avaliação</h2>
<br>
<div>
    {% for linha in resultado.split('\n') %}
    <p><strong>{{ linha }}</strong></p><br>
{% endfor %}

{% endif %}

<div style="display: flex; justify-content: center;">
    <button><a style="color: inherit;" href="/">Voltar</a></button>
</div>

{% endblock %}

app/templates/settings.html
{% extends 'base.html' %}

{% block title %}Configurações - Skreva StorIAs{% endblock %}

{% block content %}

<div style="text-align: center;">
    <h1>Configurações</h1>
     <br>
    <p>Quer se desafiar? Experimente aumentar o nível de dificuldade!</p>
</div>
<br>

<form action="{{ url_for('main.salvarconfiguracoes') }}">
    <div id="settingsDiv">

        <div id="configDiv">
            <h3>Nível de Dificuldade:</h3>
            <select onchange="selecionarDificuldade()" name="dificuldade" id="dificuldade">
                <option value="Fácil" {{ 'selected' if dificuldade == 'Fácil' }}>Fácil</option>
                <option value="Médio" {{ 'selected' if dificuldade == 'Médio' }}>Médio</option>
                <option value="Difícil" {{ 'selected' if dificuldade == 'Difícil' }}>Difícil</option>
                <option value="Personalizada" {{ 'selected' if dificuldade == 'Personalizada' }}>Personalizada</option>
            </select>
        </div>

        <div id="configDiv">
            <h3>Tempo para escrita:</h3>
            <select name="tempo" id="tempo" {{ 'disabled' if dificuldade != 'Personalizada' }}>
                <option value="120" {{ 'selected' if dificuldade == 'Difícil' }}>2 minutos</option>
                <option value="180" {{ 'selected' if dificuldade == 'Médio' }}>3 minutos</option>
                <option value="300" {{ 'selected' if dificuldade == 'Fácil' }}>5 minutos</option>
            </select>
        </div>

        <div id="configDiv">
            <h3>Limite de caracteres:</h3>
            <select name="caracteres" id="caracteres" {{ 'disabled' if dificuldade != 'Personalizada' }}>
                <option value="200" {{ 'selected' if dificuldade == 'Difícil' }}>200 caracteres</option>
                <option value="300" {{ 'selected' if dificuldade == 'Médio' }}>300 caracteres</option>
                <option value="500" {{ 'selected' if dificuldade == 'Fácil' }}>500 caracteres</option>
            </select>
        </div>

        <div style="text-align: center; width: 100%;">
            <button type="submit">Salvar</button>
        </div>
    </div>
</form>

</div>

{% endblock %}

app/templates/storia.html
{% extends "base.html" %}

{% block title %}Histórias - Skreva StorIAs{% endblock %}

{% block content %}
<a href="/historias"><button>Voltar</button></a>
<br>
<br>
<h4>Frase: {{ historia.frase }}</h4>
<br>
<div class="texto">{{ historia.historia }}</div>
<br>
<div class="avaliacoes">
    Diversão: {{ historia.diversao }} |
    Coerência: {{ historia.coerencia }} |
    Qualidade gramatical: {{ historia.gramatica }} |
    Moral: {{ historia.moral }} |
    Relação com a frase: {{ historia.relacaofrase }} |
    <strong>Média: {{ historia.media }}</strong>
</div>

{% endblock %}

app/templates/stories.html
{% extends "base.html" %}

{% block title %}Histórias - Skreva StorIAs{% endblock %}

{% block content %}
<div style="display: flex; width: 100%; justify-content: space-around; align-items: center;">
    <h1>📚 Histórias Criadas</h1>
    <p>Clique para vê-las individualmente!</p>
</div>
<br>
{% for historia in historias %}
<a href="/historia/{{ historia.id }}" style="color: inherit;">
    <div class="historia">
        <div id="divTitulo">
            <h4>Frase: {{ historia.frase }}</h4>
            <form action="/deletar_historia/{{ historia.id }}" method="POST" style="display:inline;">
                <button type="submit" style="background:none; border:none; padding:0; cursor:pointer;">
                </button>
            </form>

        </div>
        <br>
        <p>{{ historia.historia }}</p>
        <p class="avaliacoes">
            Diversão: {{ historia.diversao }} |
            Coerência: {{ historia.coerencia }} |
            Qualidade gramatical: {{ historia.gramatica }} |
            Moral: {{ historia.moral }} |
            Relação com a frase: {{ historia.relacaofrase }} |
            <strong>Média: {{ historia.media }}</strong>
        </p>
        <br>
        <p>Data da história: {{ historia.data_criacao.strftime('%d/%m/%Y %H:%M') }}</p>
    </div>
</a>
{% else %}
<p>Nenhuma história criada ainda. Comece criando uma!</p>
{% endfor %}

{% endblock %}